{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "account-service.serviceAccountName" . }}
  labels:
{{ include "account-service.labels" . | nindent 4 }}
{{- end -}}
